name: c-numbers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Set up Clang
     uses: egor-tensin/setup-clang@v1
     with:
       version: latest
       platform: x64
   - name: checkout repo
     uses: actions/checkout@main
   - name: test implementations
     run: make test
